name: Autonomous Benchmarking

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  benchmark:
    name: Performance Regression Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Benchmarks
        run: |
          pip install pytest-benchmark
          pytest tests/ --benchmark-only || echo "No benchmarks found"
