name: Autonomous Docs Lint

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Markdown
        uses: davidanson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
